services:
  - type: web
    name: EoA_Notification
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GMAIL_APP_PASSWORD  # Changed from EMAIL_PASSWORD
        sync: false
      - key: GMAIL_ADDRESS
        value: "walesalami012@gmail.com"
      - key: PORT
        value: "10000" 
      - key: FLASK_DEBUG
        value: "false"